### PR TITLE
fix audio activation

### PR DESCRIPTION
**Pull request by n1ckfg**

### CODE REVIEW

**Comment by NuclearLighthouseStudios** [comment]
Hey, can you explain what this does and why it's needed?

**Comment by n1ckfg** [comment]
The extra event listener in the index.html should enable audio on browsers that require user interaction.

**Comment by NuclearLighthouseStudios** [comment]
Ahh, that's a good idea. Which browsers need that? I tested it in Chromium and FF, and it worked without user interaction in both.

Before I merge this, could you make sure of a few things?
1. Please only include stuff relevant to the PR. No unrelated shell scripts or other changes. No .gitignore for node.
2. Move the call to `audioCtx.resume()` into the decoder class and add a function call for it so external code doesn't have to access internal members of the decoder class. Maybe something like a `Decoder.activate` function.
3. Make sure the changes don't mess up existing formatting.

Thanks for your contribution!

**Comment by n1ckfg** [comment]
OK, addressed notes and tested.

**Pull request merged**
